# [car wash]

In [0]:
USE [master]
GO

In [0]:
/****** Object:  Database [car wash]    Script Date: 11/14/2024 11:06:09 PM ******/
CREATE DATABASE [car wash]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'car wash', FILENAME = N'C:\Users\kamalkarki\OneDrive\Documents\Downloads\MSSQL16.MSSQLSERVER01\MSSQL\DATA\car wash.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'car wash_log', FILENAME = N'C:\Users\kamalkarki\OneDrive\Documents\Downloads\MSSQL16.MSSQLSERVER01\MSSQL\DATA\car wash_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [car wash] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [car wash].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [car wash] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [car wash] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [car wash] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [car wash] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [car wash] SET ARITHABORT OFF 
GO
ALTER DATABASE [car wash] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [car wash] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [car wash] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [car wash] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [car wash] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [car wash] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [car wash] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [car wash] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [car wash] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [car wash] SET  ENABLE_BROKER 
GO
ALTER DATABASE [car wash] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [car wash] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [car wash] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [car wash] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [car wash] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [car wash] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [car wash] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [car wash] SET RECOVERY FULL 
GO
ALTER DATABASE [car wash] SET  MULTI_USER 
GO
ALTER DATABASE [car wash] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [car wash] SET DB_CHAINING OFF 
GO
ALTER DATABASE [car wash] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [car wash] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [car wash] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [car wash] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'car wash', N'ON'
GO
ALTER DATABASE [car wash] SET QUERY_STORE = ON
GO
ALTER DATABASE [car wash] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

# [dbo].[tbCash]

In [0]:
USE [car wash]
GO

In [0]:
/****** Object:  Table [dbo].[tbCash]    Script Date: 11/14/2024 11:06:09 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tbCash](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[transno] [varchar](50) NULL,
	[cid] [int] NULL,
	[sid] [int] NULL,
	[price] [decimal](18, 2) NULL,
	[date] [date] NULL,
	[status] [varchar](50) NULL,
 CONSTRAINT [PK_tbCash] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[tbCompany]

In [0]:
/****** Object:  Table [dbo].[tbCompany]    Script Date: 11/14/2024 11:06:10 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tbCompany](
	[name] [varchar](50) NULL,
	[address] [varchar](50) NULL
) ON [PRIMARY]
GO

# [dbo].[tbCostofGoodSold]

In [0]:
/****** Object:  Table [dbo].[tbCostofGoodSold]    Script Date: 11/14/2024 11:06:10 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tbCostofGoodSold](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[CostName] [varchar](50) NULL,
	[Cost] [decimal](18, 2) NULL,
	[Date] [date] NULL,
 CONSTRAINT [PK_tbCostofGoodSold] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[tbCustomer]

In [0]:
/****** Object:  Table [dbo].[tbCustomer]    Script Date: 11/14/2024 11:06:10 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tbCustomer](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[fullname] [varchar](50) NULL,
	[phone] [varchar](50) NULL,
	[carno] [varchar](50) NULL,
	[carmodel] [varchar](50) NULL,
	[address] [text] NULL,
 CONSTRAINT [PK_tbCustomer] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

# [dbo].[tbEmployer]

In [0]:
/****** Object:  Table [dbo].[tbEmployer]    Script Date: 11/14/2024 11:06:10 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tbEmployer](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NULL,
	[Address] [nchar](10) NULL,
	[Phone] [varchar](50) NULL,
	[Salary] [decimal](18, 2) NULL,
	[Role] [varchar](50) NULL,
	[Gender] [varchar](50) NULL,
	[Dob] [date] NULL,
	[Password] [varchar](50) NULL,
 CONSTRAINT [PK_tbEmployer] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[tbService]

In [0]:
/****** Object:  Table [dbo].[tbService]    Script Date: 11/14/2024 11:06:10 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tbService](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[servicename] [varchar](50) NULL,
	[price] [decimal](18, 2) NULL,
 CONSTRAINT [PK_tbService] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[tbVehicle]

In [0]:
/****** Object:  Table [dbo].[tbVehicle]    Script Date: 11/14/2024 11:06:10 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tbVehicle](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NULL,
	[Class] [varchar](50) NULL,
 CONSTRAINT [PK_tbVehicle] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [DF_tbCash_status]

In [0]:
ALTER TABLE [dbo].[tbCash] ADD  CONSTRAINT [DF_tbCash_status]  DEFAULT ('Pending') FOR [status]
GO

# [car wash]

In [0]:
USE [master]
GO

In [0]:
ALTER DATABASE [car wash] SET  READ_WRITE 
GO